### ISSUE TITLE
Error when using blur shadow with setdigitfont command

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [persiantex/xepersian#11]
```

\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{shadows.blur}
\usepackage{xepersian}
\settextfont{Yas}
%استفاده از 2 دستور زیر با گزینه مثال shadows.blur خطا دارد!
\setdigitfont{Yas}
%\settextdigitfont{Yas}
% استفاده از دستور زیر مشکلی ندارد.
%\setmathdigitfont{Yas}

\begin{document}
تست
\begin{tikzpicture}
\filldraw[fill=white, draw=black,blur shadow](0,0) rectangle (1,1);
\end{tikzpicture}

\end{document}
```
output:
[shadows-blur-TL2020.log](https://github.com/persiantex/xepersian/files/4632585/shadows-blur-TL2020.log)

[shadows-blur-TL2020.pdf](https://github.com/persiantex/xepersian/files/4632586/shadows-blur-TL2020.pdf)

**Comment by vafakhalighi** [comment]
Thanks for your report. This seems to be caused by the `\settextdigitfont` control sequence. You can in the meanwhile, use the control sequence `\setmathdigitfont` instead the control sequence `\setdigitfont` to set the digit font in math mode.

**Comment by mojtabaahmadi2020tl** [comment]
Thanks, I controlled with `\TextDigitFontOff` and `\TextDigitFontOn`

**Comment by mojtabaahmadi2020tl** [comment]
درود جناب وفا
جهت اطلاع: در تک لایو 2021 این مشکل حل شده
