### ISSUE TITLE
written permission -> nonfree

### ISSUE THREAD

**Issue by kberry** [persiantex/xepersian#15]
Hi Vafa - requiring your written permission to use a feature makes a package nonfree. I understand you have good reason to do this, but I have no alternative but to remove it from TeX Live as a result, which I just did. Just wanted to let you know. Hope the situation gets better one day. --best, karl.

**Comment by vafakhalighi** [comment]
Dear Karl,

Thanks for your report. I do not wish to penalize and make life hard for the users of the package as many are at the middle of preparing their books and theses with this package. I decided to remove the restriction entirely and uploaded a new version to CTAN. It should be free now.

Best wishes, Vafa
