### ISSUE TITLE
Problem with \DefaultMathsDigits and \PersianMathsDigits Switches

### ISSUE THREAD

**Issue by aliprd** [persiantex/xepersian#30]
Dear Vafa

First I would like to thank you for your superb work that brings us the XePersian package!

After the recent update, the two macros of \DefaultMathsDigits and \PersianMathsDigits have stopped working. I encountered this issue with both MikTex and Tex Live on Windows platform. Here is a MWE:

`\documentclass[a4paper,twoside,fleqn]{report}`

`\usepackage[a4paper]{geometry}`
`\usepackage{amsmath}`
`\usepackage{mathspec}`
`\usepackage{xepersian}`

`\settextfont{XB Zar}`
`\setlatintextfont{Times New Roman}`

`\setlength{\mathindent}{1cm}`
`\setmathdigitfont{XB Zar}`
`\DefaultMathsDigits`

`\newenvironment{parsimath}{\PersianMathsDigits}{}`

`\newgeometry{left=2.5cm,right=3cm,top=3cm,bottom=2.5cm}`

`\begin{document}`
	
`\begin{equation}`
`	{P_{QN}} = 10\log \left( {\frac{{V_{LSB}^2}}{{12{f_s}}}} \right) = 20\log \left( {{V_{ref}}} \right) - 6.02N - 10.79 - 10\log \left( {{f_s}} \right)`
`\end{equation}`

`\begin{parsimath}`
`\begin{equation}`
`	{P_{QN}} = 10\log \left( {\frac{{V_{LSB}^2}}{{12{f_s}}}} \right) = 20\log \left( {{V_{ref}}} \right) - 6.02N - 10.79 - 10\log \left( {{f_s}} \right)`
`\end{equation}`
`\end{parsimath}`
	
`\end{document}`

The output: [MWE.pdf](https://github.com/persiantex/xepersian/files/8813858/MWE.pdf)

The comiler gives errors as "Undefined control sequence. \DefaultMathsDigits" and "Undefined control sequence. \PersianMathsDigits" while both equations are typeset via Persian digits, though the first one should be in English.

I appreciate your help on this matter.

**Comment by kvafa** [comment]
Thanks for this. Change `Maths` (Australian spelling) to `Math` (American Spelling); So use `\DefaultMathDigits` instead `\DefaultMathsDigits` and `\PersianMathDigits` instead `\PersianMathsDigits`. 

Please also note that this is an old repository and I do not check it very often. Please use [this one](https://github.com/kvafa/xepersian/issues) in future.

**Comment by aliprd** [comment]
Thanks a lot! That solved the problem.
